// Mock data from original zip folder - exact restaurants and dishes

export const MOCK_DISHES = [
  {
    id: 'd1',
    name: 'Grilled Chicken Quinoa Bowl',
    price: 350,
    originalPrice: 350,
    description: 'High protein grilled chicken with quinoa, steamed broccoli, and lemon dressing.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    tags: ['Non-Veg', 'High Protein', 'Low Carb', 'Gluten Free'],
    calories: 450,
    protein: 40,
    carbs: 30,
    fats: 10,
    sodium: 400,
    rating: 4.8,
    preparationTime: 20,
  },
  {
    id: 'd2',
    name: 'Butter Chicken & Naan',
    price: 450,
    originalPrice: 600,
    description: 'Rich creamy tomato gravy with tender chicken pieces served with butter naan.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
    tags: ['Non-Veg', 'Oily', 'Spicy'],
    calories: 850,
    protein: 25,
    carbs: 60,
    fats: 50,
    sodium: 900,
    rating: 4.5,
    preparationTime: 30,
  },
  {
    id: 'd3',
    name: 'Paneer Tikka Salad',
    price: 280,
    originalPrice: 280,
    description: 'Fresh garden salad topped with smokey grilled paneer cubes and mint chutney.',
    image: '/images/paneer salad.jpg',
    tags: ['Veg', 'High Protein', 'Gluten Free'],
    calories: 300,
    protein: 18,
    carbs: 15,
    fats: 15,
    sodium: 300,
    rating: 4.6,
    preparationTime: 15,
  },
  {
    id: 'd4',
    name: 'Double Cheese Burger',
    price: 199,
    originalPrice: 250,
    description: 'Juicy beef/chicken patty with double cheddar cheese, caramelized onions and mayo.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    tags: ['Non-Veg', 'Oily', 'Street Food', 'Fast Food'],
    calories: 900,
    protein: 20,
    carbs: 50,
    fats: 60,
    sodium: 1200,
    rating: 4.2,
    preparationTime: 25,
  },
  {
    id: 'd5',
    name: 'Oats & Berries Smoothie',
    price: 220,
    originalPrice: 220,
    description: 'Sugar-free almond milk smoothie with rolled oats, mixed berries and chia seeds.',
    image: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Vegan', 'Sweet', 'Gluten Free', 'Beverage'],
    calories: 250,
    protein: 8,
    carbs: 40,
    fats: 5,
    sodium: 50,
    rating: 4.9,
    preparationTime: 10,
  },
  {
    id: 'd6',
    name: 'Grilled Salmon with Asparagus',
    price: 550,
    originalPrice: 600,
    description: 'Omega-3 rich atlantic salmon fillet grilled to perfection with roasted asparagus.',
    image: '/images/salmon ans aspergas.jpg',
    tags: ['Non-Veg', 'High Protein', 'Low Carb', 'Gluten Free', 'Seafood'],
    calories: 400,
    protein: 35,
    carbs: 5,
    fats: 20,
    sodium: 350,
    rating: 4.9,
    preparationTime: 25,
  },
  {
    id: 'd7',
    name: 'Pepperoni Pizza',
    price: 399,
    originalPrice: 450,
    description: 'Classic pepperoni pizza with mozzarella cheese and tomato basil sauce.',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=80',
    tags: ['Non-Veg', 'Oily', 'Spicy', 'Fast Food'],
    calories: 1200,
    protein: 30,
    carbs: 100,
    fats: 65,
    sodium: 1500,
    rating: 4.4,
    preparationTime: 35,
  },
  {
    id: 'd8',
    name: 'Dal Makhani & Jeera Rice',
    price: 320,
    originalPrice: 350,
    description: 'Slow cooked black lentils with cream and butter, served with cumin rice.',
    image: '/images/dal makhani and jeera rice.jpg',
    tags: ['Veg', 'Oily'],
    calories: 600,
    protein: 15,
    carbs: 80,
    fats: 25,
    sodium: 600,
    rating: 4.7,
    preparationTime: 20,
  },
  {
    id: 'd9',
    name: 'Spicy Chicken Tacos',
    price: 290,
    originalPrice: 290,
    description: 'Soft shell tacos filled with spicy shredded chicken, salsa and guacamole.',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=800&q=80',
    tags: ['Non-Veg', 'Spicy', 'Street Food'],
    calories: 450,
    protein: 22,
    carbs: 35,
    fats: 20,
    sodium: 700,
    rating: 4.5,
    preparationTime: 15,
  },
  {
    id: 'd10',
    name: 'Exotic Fruit Bowl',
    price: 250,
    originalPrice: 300,
    description: 'Seasonal mix of kiwi, dragon fruit, papaya, and watermelon.',
    image: 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Vegan', 'Sweet', 'Gluten Free'],
    calories: 150,
    protein: 2,
    carbs: 35,
    fats: 0,
    sodium: 10,
    rating: 4.8,
    preparationTime: 5,
  },
  {
    id: 'd11',
    name: 'Spaghetti Aglio e Olio',
    price: 380,
    originalPrice: 420,
    description: 'Classic Italian pasta with garlic, olive oil, parsley, and chili flakes.',
    image: 'https://images.unsplash.com/photo-1551183053-bf91b1d3116c?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Oily', 'Spicy'],
    calories: 550,
    protein: 12,
    carbs: 70,
    fats: 25,
    sodium: 400,
    rating: 4.6,
    preparationTime: 20,
  },
  {
    id: 'd12',
    name: 'Schezwan Noodles',
    price: 260,
    originalPrice: 260,
    description: 'Stir-fried hakka noodles tossed in spicy schezwan sauce with vegetables.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Vegan', 'Spicy', 'Oily', 'Street Food'],
    calories: 600,
    protein: 10,
    carbs: 85,
    fats: 22,
    sodium: 950,
    rating: 4.3,
    preparationTime: 15,
  },
  {
    id: 'd13',
    name: 'Mysore Masala Dosa',
    price: 180,
    originalPrice: 200,
    description: 'Crispy fermented crepe smeared with red chutney and filled with potato masala.',
    image: '/images/Mysore masala dosa.jpg',
    tags: ['Veg', 'Spicy', 'Gluten Free'],
    calories: 350,
    protein: 8,
    carbs: 60,
    fats: 12,
    sodium: 450,
    rating: 4.7,
    preparationTime: 10,
  },
  {
    id: 'd14',
    name: 'Veg Dim Sum Basket',
    price: 320,
    originalPrice: 350,
    description: 'Steamed dumplings filled with finely chopped bok choy, mushroom and corn.',
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Vegan', 'Low Carb'],
    calories: 200,
    protein: 6,
    carbs: 30,
    fats: 5,
    sodium: 300,
    rating: 4.5,
    preparationTime: 15,
  },
  {
    id: 'd15',
    name: 'Hyderabadi Mutton Biryani',
    price: 550,
    originalPrice: 650,
    description: 'Aromatic basmati rice cooked with marinated mutton spices and saffron.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    tags: ['Non-Veg', 'Spicy', 'Oily'],
    calories: 950,
    protein: 35,
    carbs: 90,
    fats: 45,
    sodium: 1100,
    rating: 4.9,
    preparationTime: 45,
  },
  {
    id: 'd16',
    name: 'Belgian Chocolate Waffle',
    price: 240,
    originalPrice: 280,
    description: 'Warm crispy waffle topped with melted dark chocolate and vanilla ice cream.',
    image: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Sweet'],
    calories: 650,
    protein: 8,
    carbs: 85,
    fats: 30,
    sodium: 200,
    rating: 4.8,
    preparationTime: 10,
  },
  {
    id: 'd17',
    name: 'Sushi Platter',
    price: 899,
    originalPrice: 1000,
    description: 'Assorted maki rolls including Salmon Avocado, Tuna and California Rolls.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    tags: ['Non-Veg', 'High Protein', 'Gluten Free', 'Seafood'],
    calories: 450,
    protein: 25,
    carbs: 60,
    fats: 10,
    sodium: 600,
    rating: 4.8,
    preparationTime: 25,
  },
  {
    id: 'd18',
    name: 'Tofu Poke Bowl',
    price: 420,
    originalPrice: 450,
    description: 'Marinated tofu, edamame, cucumber, and avocado over brown rice.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Vegan', 'High Protein', 'Gluten Free'],
    calories: 400,
    protein: 20,
    carbs: 45,
    fats: 15,
    sodium: 350,
    rating: 4.6,
    preparationTime: 15,
  },
  {
    id: 'd19',
    name: 'Rava Idli',
    price: 150,
    originalPrice: 150,
    description: 'Steamed semolina cakes served with coconut chutney and sambar.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Vegan', 'Low Carb'],
    calories: 180,
    protein: 6,
    carbs: 30,
    fats: 2,
    sodium: 250,
    rating: 4.5,
    preparationTime: 10,
  },
  {
    id: 'd20',
    name: 'Tiramisu',
    price: 350,
    originalPrice: 350,
    description: 'Coffee-flavoured Italian dessert with mascarpone cheese and cocoa.',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Sweet'],
    calories: 450,
    protein: 6,
    carbs: 40,
    fats: 25,
    sodium: 150,
    rating: 4.9,
    preparationTime: 0,
  },
  {
    id: 'd21',
    name: 'Chicken Tikka Masala',
    price: 480,
    originalPrice: 550,
    description: 'Chunks of roasted marinated chicken in a spiced curry sauce.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    tags: ['Non-Veg', 'Spicy', 'Oily', 'High Protein'],
    calories: 750,
    protein: 30,
    carbs: 25,
    fats: 45,
    sodium: 850,
    rating: 4.8,
    preparationTime: 35,
  },
  {
    id: 'd22',
    name: 'Veg Supreme Pizza',
    price: 450,
    originalPrice: 500,
    description: 'Loaded with bell peppers, onions, mushrooms, olives and corn.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Fast Food', 'Oily'],
    calories: 1100,
    protein: 20,
    carbs: 120,
    fats: 50,
    sodium: 1300,
    rating: 4.5,
    preparationTime: 30,
  },
  {
    id: 'd23',
    name: 'Cold Coffee with Ice Cream',
    price: 180,
    originalPrice: 200,
    description: 'Classic blended cold coffee topped with a scoop of vanilla ice cream.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Beverage', 'Sweet'],
    calories: 350,
    protein: 5,
    carbs: 45,
    fats: 15,
    sodium: 80,
    rating: 4.7,
    preparationTime: 5,
  },
  {
    id: 'd24',
    name: 'Masala Chai',
    price: 50,
    originalPrice: 50,
    description: 'Traditional Indian tea brewed with aromatic spices and herbs.',
    image: '/images/masala chai.jpg',
    tags: ['Veg', 'Beverage', 'Sweet'],
    calories: 120,
    protein: 2,
    carbs: 20,
    fats: 3,
    sodium: 10,
    rating: 4.9,
    preparationTime: 5,
  },
  {
    id: 'd25',
    name: 'Fish & Chips',
    price: 420,
    originalPrice: 480,
    description: 'Crispy batter-fried fish fillets served with french fries and tartar sauce.',
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80',
    tags: ['Non-Veg', 'Seafood', 'Oily', 'Fast Food'],
    calories: 850,
    protein: 25,
    carbs: 80,
    fats: 45,
    sodium: 950,
    rating: 4.6,
    preparationTime: 25,
  },
  {
    id: 'd26',
    name: 'Club Sandwich',
    price: 250,
    originalPrice: 280,
    description: 'Triple decker sandwich with chicken, egg, lettuce, cheese and tomato.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    tags: ['Non-Veg', 'Fast Food', 'High Protein'],
    calories: 550,
    protein: 28,
    carbs: 45,
    fats: 25,
    sodium: 800,
    rating: 4.4,
    preparationTime: 15,
  },
  {
    id: 'd27',
    name: 'Veg Manchurian Dry',
    price: 220,
    originalPrice: 250,
    description: 'Fried vegetable balls tossed in spicy, sweet and tangy manchurian sauce.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Vegan', 'Street Food', 'Spicy'],
    calories: 400,
    protein: 5,
    carbs: 55,
    fats: 18,
    sodium: 900,
    rating: 4.3,
    preparationTime: 20,
  },
  {
    id: 'd28',
    name: 'Goan Prawn Curry',
    price: 580,
    originalPrice: 650,
    description: 'Prawns cooked in a coconut milk based curry with tamarind and mild spices.',
    image: '/images/Goan prawn curry.jpg',
    tags: ['Non-Veg', 'Seafood', 'Spicy', 'Gluten Free'],
    calories: 550,
    protein: 28,
    carbs: 15,
    fats: 40,
    sodium: 750,
    rating: 4.8,
    preparationTime: 30,
  },
  {
    id: 'd29',
    name: 'Chole Bhature',
    price: 180,
    originalPrice: 200,
    description: 'Spicy chickpea curry served with fried leavened bread.',
    image: '/images/Chole bhature.jpg',
    tags: ['Veg', 'Street Food', 'Oily', 'Spicy'],
    calories: 800,
    protein: 18,
    carbs: 110,
    fats: 35,
    sodium: 900,
    rating: 4.7,
    preparationTime: 20,
  },
  {
    id: 'd30',
    name: 'Rasmalai (2 Pcs)',
    price: 120,
    originalPrice: 120,
    description: 'Soft cottage cheese dumplings soaked in sweetened, thickened milk.',
    image: '/images/Rasmalai-2pcs.jpg',
    tags: ['Veg', 'Sweet', 'Gluten Free'],
    calories: 250,
    protein: 8,
    carbs: 35,
    fats: 12,
    sodium: 40,
    rating: 4.9,
    preparationTime: 5,
  },
  {
    id: 'd31',
    name: 'Vegan Avocado Salad',
    price: 380,
    originalPrice: 420,
    description: 'Fresh mixed greens, avocado, cherry tomatoes, and balsamic glaze.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    tags: ['Veg', 'Vegan', 'Gluten Free', 'Low Carb'],
    calories: 280,
    protein: 5,
    carbs: 12,
    fats: 22,
    sodium: 150,
    rating: 4.6,
    preparationTime: 10,
  },
  {
    id: 'd32',
    name: 'BBQ Chicken Wings',
    price: 320,
    originalPrice: 380,
    description: 'Chicken wings glazed in smoky barbecue sauce.',
    image: 'https://images.unsplash.com/photo-1527477396000-64ca9c00173f?auto=format&fit=crop&w=800&q=80',
    tags: ['Non-Veg', 'Fast Food', 'High Protein', 'Spicy'],
    calories: 600,
    protein: 35,
    carbs: 10,
    fats: 40,
    sodium: 900,
    rating: 4.5,
    preparationTime: 20,
  },
  {
    id: 'd33',
    name: 'Mango Lassi',
    price: 100,
    originalPrice: 120,
    description: 'Creamy yogurt drink blended with fresh ripe mango pulp.',
    image: null, // Will be generated by AI
    tags: ['Veg', 'Beverage', 'Sweet', 'Gluten Free'],
    calories: 280,
    protein: 8,
    carbs: 45,
    fats: 8,
    sodium: 50,
    rating: 4.8,
    preparationTime: 5,
  }
];

export const MOCK_RESTAURANTS = [
  {
    id: 'r1',
    name: 'FitBite Kitchen',
    cuisine: ['Healthy', 'Salads', 'Continental'],
    rating: 4.7,
    deliveryTime: 25,
    priceRange: '$$',
    menu: [MOCK_DISHES[0], MOCK_DISHES[2], MOCK_DISHES[4], MOCK_DISHES[5], MOCK_DISHES[9], MOCK_DISHES[29], MOCK_DISHES[3], MOCK_DISHES[6], MOCK_DISHES[10], MOCK_DISHES[11], MOCK_DISHES[12], MOCK_DISHES[23], MOCK_DISHES[24], MOCK_DISHES[32]],
    priceHistory: [
      { day: 'Mon', avgPrice: 300 },
      { day: 'Tue', avgPrice: 300 },
      { day: 'Wed', avgPrice: 310 },
      { day: 'Thu', avgPrice: 300 },
      { day: 'Fri', avgPrice: 320 },
      { day: 'Sat', avgPrice: 350 },
      { day: 'Sun', avgPrice: 350 },
    ],
    coordinates: { lat: 28.6328, lng: 77.2197 },
    address: "Block A, Connaught Place, New Delhi"
  },
  {
    id: 'r2',
    name: 'Punjabi Tadka',
    cuisine: ['North Indian', 'Mughlai'],
    rating: 4.3,
    deliveryTime: 40,
    priceRange: '$$$',
    menu: [MOCK_DISHES[1], MOCK_DISHES[7], MOCK_DISHES[14], MOCK_DISHES[27], MOCK_DISHES[2], MOCK_DISHES[8], MOCK_DISHES[20], MOCK_DISHES[28], MOCK_DISHES[30], MOCK_DISHES[23], MOCK_DISHES[32]],
    priceHistory: [
      { day: 'Mon', avgPrice: 400 },
      { day: 'Tue', avgPrice: 400 },
      { day: 'Wed', avgPrice: 400 },
      { day: 'Thu', avgPrice: 420 },
      { day: 'Fri', avgPrice: 550 },
      { day: 'Sat', avgPrice: 550 },
      { day: 'Sun', avgPrice: 500 },
    ],
    coordinates: { lat: 28.6506, lng: 77.2304 },
    address: "Chandni Chowk, Old Delhi"
  },
  {
    id: 'r3',
    name: 'The Italian Job',
    cuisine: ['Italian', 'Continental'],
    rating: 4.5,
    deliveryTime: 35,
    priceRange: '$$$',
    menu: [MOCK_DISHES[6], MOCK_DISHES[10], MOCK_DISHES[19], MOCK_DISHES[20], MOCK_DISHES[4], MOCK_DISHES[5], MOCK_DISHES[12], MOCK_DISHES[13], MOCK_DISHES[17]],
    priceHistory: [
      { day: 'Mon', avgPrice: 380 },
      { day: 'Tue', avgPrice: 380 },
      { day: 'Wed', avgPrice: 390 },
      { day: 'Thu', avgPrice: 400 },
      { day: 'Fri', avgPrice: 420 },
      { day: 'Sat', avgPrice: 450 },
      { day: 'Sun', avgPrice: 450 },
    ],
    coordinates: { lat: 28.5921, lng: 77.2272 },
    address: "Khan Market, New Delhi"
  },
  {
    id: 'r4',
    name: 'Wok & Roll',
    cuisine: ['Asian', 'Chinese', 'Japanese'],
    rating: 4.4,
    deliveryTime: 30,
    priceRange: '$$',
    menu: [MOCK_DISHES[11], MOCK_DISHES[13], MOCK_DISHES[16], MOCK_DISHES[25], MOCK_DISHES[1], MOCK_DISHES[7], MOCK_DISHES[14], MOCK_DISHES[17], MOCK_DISHES[21], MOCK_DISHES[24]],
    priceHistory: [
      { day: 'Mon', avgPrice: 250 },
      { day: 'Tue', avgPrice: 250 },
      { day: 'Wed', avgPrice: 260 },
      { day: 'Thu', avgPrice: 260 },
      { day: 'Fri', avgPrice: 280 },
      { day: 'Sat', avgPrice: 300 },
      { day: 'Sun', avgPrice: 300 },
    ],
    coordinates: { lat: 28.5677, lng: 77.2433 },
    address: "Central Market, Lajpat Nagar II"
  },
  {
    id: 'r5',
    name: 'Dosa Plaza',
    cuisine: ['South Indian'],
    rating: 4.6,
    deliveryTime: 20,
    priceRange: '$',
    menu: [MOCK_DISHES[12], MOCK_DISHES[18], MOCK_DISHES[22], MOCK_DISHES[0], MOCK_DISHES[2], MOCK_DISHES[4], MOCK_DISHES[5], MOCK_DISHES[6]],
    priceHistory: [
      { day: 'Mon', avgPrice: 150 },
      { day: 'Tue', avgPrice: 150 },
      { day: 'Wed', avgPrice: 150 },
      { day: 'Thu', avgPrice: 160 },
      { day: 'Fri', avgPrice: 180 },
      { day: 'Sat', avgPrice: 200 },
      { day: 'Sun', avgPrice: 200 },
    ],
    coordinates: { lat: 28.6219, lng: 77.2811 },
    address: "Vikas Marg, Laxmi Nagar"
  },
  {
    id: 'r6',
    name: 'Sweet Tooth',
    cuisine: ['Desserts', 'Bakery'],
    rating: 4.8,
    deliveryTime: 15,
    priceRange: '$$',
    menu: [MOCK_DISHES[15], MOCK_DISHES[19], MOCK_DISHES[4], MOCK_DISHES[29], MOCK_DISHES[9], MOCK_DISHES[23], MOCK_DISHES[24], MOCK_DISHES[26], MOCK_DISHES[30], MOCK_DISHES[31]],
    priceHistory: [
      { day: 'Mon', avgPrice: 200 },
      { day: 'Tue', avgPrice: 200 },
      { day: 'Wed', avgPrice: 220 },
      { day: 'Thu', avgPrice: 220 },
      { day: 'Fri', avgPrice: 250 },
      { day: 'Sat', avgPrice: 250 },
      { day: 'Sun', avgPrice: 250 },
    ],
    coordinates: { lat: 28.6448, lng: 77.1896 },
    address: "Ajmal Khan Road, Karol Bagh"
  },
  {
    id: 'r7',
    name: 'Grill & Chill',
    cuisine: ['American', 'Fast Food'],
    rating: 4.2,
    deliveryTime: 30,
    priceRange: '$$',
    menu: [MOCK_DISHES[3], MOCK_DISHES[24], MOCK_DISHES[31], MOCK_DISHES[0], MOCK_DISHES[1], MOCK_DISHES[6], MOCK_DISHES[8], MOCK_DISHES[10], MOCK_DISHES[25]],
    priceHistory: [
      { day: 'Mon', avgPrice: 220 },
      { day: 'Tue', avgPrice: 220 },
      { day: 'Wed', avgPrice: 240 },
      { day: 'Thu', avgPrice: 240 },
      { day: 'Fri', avgPrice: 280 },
      { day: 'Sat', avgPrice: 300 },
      { day: 'Sun', avgPrice: 300 },
    ],
    coordinates: { lat: 28.5448, lng: 77.2066 },
    address: "Hauz Khas Village, New Delhi"
  },
  {
    id: 'r8',
    name: 'The Caffeine Fix',
    cuisine: ['Cafe', 'Beverages'],
    rating: 4.9,
    deliveryTime: 15,
    priceRange: '$$',
    menu: [MOCK_DISHES[22], MOCK_DISHES[23], MOCK_DISHES[24], MOCK_DISHES[15], MOCK_DISHES[19], MOCK_DISHES[26], MOCK_DISHES[29], MOCK_DISHES[30], MOCK_DISHES[31], MOCK_DISHES[32]],
    priceHistory: [
      { day: 'Mon', avgPrice: 180 },
      { day: 'Tue', avgPrice: 180 },
      { day: 'Wed', avgPrice: 180 },
      { day: 'Thu', avgPrice: 180 },
      { day: 'Fri', avgPrice: 200 },
      { day: 'Sat', avgPrice: 220 },
      { day: 'Sun', avgPrice: 220 },
    ],
    coordinates: { lat: 28.5244, lng: 77.1855 },
    address: "Select Citywalk, Saket"
  },
  {
    id: 'r9',
    name: 'Spice Route',
    cuisine: ['Indian', 'Curry', 'Mughlai'],
    rating: 4.7,
    deliveryTime: 45,
    priceRange: '$$$',
    menu: [MOCK_DISHES[20], MOCK_DISHES[27], MOCK_DISHES[32], MOCK_DISHES[1], MOCK_DISHES[7], MOCK_DISHES[14], MOCK_DISHES[21], MOCK_DISHES[28], MOCK_DISHES[30]],
    priceHistory: [
      { day: 'Mon', avgPrice: 450 },
      { day: 'Tue', avgPrice: 450 },
      { day: 'Wed', avgPrice: 480 },
      { day: 'Thu', avgPrice: 480 },
      { day: 'Fri', avgPrice: 550 },
      { day: 'Sat', avgPrice: 600 },
      { day: 'Sun', avgPrice: 600 },
    ],
    coordinates: { lat: 28.6139, lng: 77.2090 },
    address: "Sansad Marg, New Delhi"
  },
  {
    id: 'r10',
    name: 'Burger King',
    cuisine: ['Fast Food', 'American', 'Burgers'],
    rating: 4.4,
    deliveryTime: 20,
    priceRange: '$$',
    menu: [MOCK_DISHES[3], MOCK_DISHES[8], MOCK_DISHES[25], MOCK_DISHES[31], MOCK_DISHES[0], MOCK_DISHES[1], MOCK_DISHES[6], MOCK_DISHES[10], MOCK_DISHES[24], MOCK_DISHES[30]],
    priceHistory: [
      { day: 'Mon', avgPrice: 240 },
      { day: 'Tue', avgPrice: 240 },
      { day: 'Wed', avgPrice: 250 },
      { day: 'Thu', avgPrice: 250 },
      { day: 'Fri', avgPrice: 280 },
      { day: 'Sat', avgPrice: 300 },
      { day: 'Sun', avgPrice: 300 },
    ],
    coordinates: { lat: 28.5355, lng: 77.3910 },
    address: "Sector 18, Noida"
  },
  {
    id: 'r11',
    name: 'Tandoor Express',
    cuisine: ['North Indian', 'Tandoor', 'Mughlai'],
    rating: 4.6,
    deliveryTime: 35,
    priceRange: '$$',
    menu: [MOCK_DISHES[1], MOCK_DISHES[7], MOCK_DISHES[20], MOCK_DISHES[28], MOCK_DISHES[2], MOCK_DISHES[14], MOCK_DISHES[21], MOCK_DISHES[27], MOCK_DISHES[30], MOCK_DISHES[32]],
    priceHistory: [
      { day: 'Mon', avgPrice: 320 },
      { day: 'Tue', avgPrice: 320 },
      { day: 'Wed', avgPrice: 330 },
      { day: 'Thu', avgPrice: 340 },
      { day: 'Fri', avgPrice: 380 },
      { day: 'Sat', avgPrice: 400 },
      { day: 'Sun', avgPrice: 380 },
    ],
    coordinates: { lat: 28.6000, lng: 77.2200 },
    address: "Rajouri Garden, New Delhi"
  }
];
